import assert from "node:assert/strict";
import { test } from "node:test";
import { parseEditorDataSources } from "../editor-data-sources.js";
import {
  createManagedFormulaDataSource,
  findNormalizationCandidate,
  normalizeManagedColumns,
} from "../managed-table.js";

test("editor message parsing accepts reference groups generated by normalization", () => {
  const source = createManagedFormulaDataSource("contacts");
  source.columns = [
    { id: "c1", name: "name", constraint: "any" },
    { id: "c2", name: "city", constraint: "any" },
    { id: "c3", name: "country", constraint: "any" },
  ];
  source.rows = [
    ["Alice", "Tokyo", "JP"],
    ["Bob", "Tokyo", "JP"],
    ["Chika", "Osaka", "JP"],
  ].map((values, row) => ({
    id: `r${row + 1}`,
    cells: values.map((value) => ({
      content: {
        kind: "literal" as const,
        value: { type: "string" as const, value },
      },
    })),
  }));
  const candidate = findNormalizationCandidate(source);
  assert.ok(candidate);
  const normalized = normalizeManagedColumns(source, candidate, "contacts-detail");
  const payload = JSON.parse(JSON.stringify([normalized.source, normalized.target]));

  assert.deepEqual(parseEditorDataSources(payload), [
    normalized.source,
    normalized.target,
  ]);
  payload[0].referenceGroups[0].rowIds = "invalid";
  assert.equal(parseEditorDataSources(payload), undefined);
});
